name: 하루하나 목 API 서버 배포

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: 소스코드 체크아웃
        uses: actions/checkout@v4

      - name: 의존성 설치
        run: npm install

      - name: 포트 확인 및 프로세스 종료
        run: |
          pid=$(lsof -t -i:8080) || true
          if [ ! -z "$pid" ]; then
            kill -9 $pid || true
          fi

      - name: API 서버 시작
        run: nohup npm start > output.log 2>&1 &
