name: 하루하나 API 서버 배포

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: 소스코드 체크아웃
        uses: actions/checkout@v4

      - name: Node.js 설정
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: PM2 전역 설치
        run: npm install -g pm2

      - name: 의존성 설치
        run: npm install

      - name: 이전 프로세스 정리
        run: pm2 delete haruhana-api || true

      - name: API 서버 시작
        run: pm2 start server.js --name "haruhana-api"
